# Starship Configuration
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$python\
$java\
$golang\
$rust\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " 🔒"
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
symbol = "🌱 "
format = "[$symbol$branch]($style) "
style = "bright-green"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
symbol = "🐍 "
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
symbol = "⬢ "
format = "[$symbol($version )]($style)"

[java]
symbol = "☕ "
format = "[$symbol($version )]($style)"

[golang]
symbol = "🐹 "
format = "[$symbol($version )]($style)"

[rust]
symbol = "🦀 "
format = "[$symbol($version )]($style)"
